DEFAULT_NET_IP = "0.0.0.0"


BUTTON_FG_COLOR = "Black"
BUTTON_SELECTED_COLOR = "#615757"

APP_COUNT = 3

PAD_X = 30
PAD_Y = 30

SIZE_X = 1000
SIZE_Y = 580

FRAME_CORNER_RADIUS = 25

CENTER_WINDOW = SIZE_X / 2
FRAME_SIZE_X = SIZE_X - 2 * PAD_X
CONNECTION_FRAME_SIZE_X = (SIZE_X - 3 * PAD_X) / 5 * 2
SIGNUP_FRAME_SIZE_X = CONNECTION_FRAME_SIZE_X * 1.5
FRAME_SIZE_Y = SIZE_Y - 5 * PAD_Y

TITLE_PLACEMENT_Y = PAD_Y

CONNECTION_FRAME_CENTER = CONNECTION_FRAME_SIZE_X / 2
SIGNUP_FRAME_CENTER = SIGNUP_FRAME_SIZE_X / 2

FRAME_Y_ORIGIN = 3 * PAD_Y
FRAME_BUTTON_Y = FRAME_SIZE_Y - PAD_Y

APPFRAME_SIZE_X = (SIZE_X - (APP_COUNT + 1) * PAD_X) / APP_COUNT
APPFRAME_CENTER = APPFRAME_SIZE_X / 2

APPFRAME_DESC_LABEL_Y = FRAME_SIZE_Y - 3 * PAD_Y

INPUTFRAME_SIZE_X = (SIZE_X - 3 * PAD_X) / 4 * 1.5
TITLE_OUTPUT_SIZE_X = SIZE_X - 3 * PAD_X - INPUTFRAME_SIZE_X 

TITLE_FRAME_SIZE_Y = 120
OUTPUT_FRAME_SIZE_Y = FRAME_SIZE_Y - TITLE_FRAME_SIZE_Y - PAD_Y

INPUTFRAME_CENTER = INPUTFRAME_SIZE_X / 2